### ISSUE TITLE
Error on `composer install` 

### ISSUE THREAD

**Issue by EwanValentine** [pusher/pusher-http-php#101]
```
  [RuntimeException]
  File at "/var/www/api/vendor/pusher/pusher-php-server/lib//Pusher.php" does not exist, check your classmap definitions
```

**Comment by zimbatm** [comment]
Can you list the files that you have in `/var/www/api/vendor/pusher/pusher-php-server` and `/var/www/api/vendor/pusher/pusher-php-server/lib` ?

**Comment by zimbatm** [comment]
The double slash is strange. This library is widely used and you are the first user reporting this issue so I would be inclined to thing it's an issue with your setup.

Let me know if you find anything else.
