### ISSUE TITLE
More Intuitive Error Message When the Response Status Code Is 0

### ISSUE THREAD

**Issue by bookercodes** [pusher/pusher-http-php#115]
Hi,

Someone I spoke to on ZenDesk mentioned that when running the following code:

``` php
<?php
 require('Pusher.php');

 $options = array(
     'encrypted' => true
 );
 $pusher = new Pusher(
     'xxx',
     'xxx',
     'xxx',
     $options
);

 $data['message'] = 'hello world';
 $pusher->trigger('test_channel', 'my_event', $data);
?>
```

... He or she received the following response:

```
array(2) { ["body"]=> bool(false) ["status"]=> int(0)
```

A status code of `0` is quite pecuilar, no?

@jameshfisher and I did some research and found [this](http://stackoverflow.com/questions/10227879/php-curl-http-code-return-0) StackOverflow answer, which states:

> If you connect with the server, then you can get a return code from it, otherwise it will fail and you get a 0. So if you try to connect to "www.google.com/lksdfk" you will get a return code of 400, if you go directly to google.com, you will get 302 (and then 200 if you forward to the next page... well I do because it forwards to google.com.br, so you might not get that), and if you go to "googlecom" you will get a 0 (host no found), so with the last one, there is nobody to send a code back.

I have asked the user to enable debugging and to report back. In the meantime, @jameshfisher suggested that I open an issue requesting a more intuitive error in the case that the `status` is `0`.

**Comment by WillSewell** [comment]
Should be fixed by https://github.com/pusher/pusher-http-php/pull/179

**Comment by WillSewell** [comment]
Fixed in https://github.com/pusher/pusher-http-php/pull/195
