### ISSUE TITLE
Do not send events [ Unknown auth_key]

### ISSUE THREAD

**Issue by chulifo** [pusher/pusher-http-php#118]
I am using the following code:

```
`require('pusher-http-php-master/lib/Pusher.php');
error_reporting(E_ALL);
$app_id = '*'; 
$app_key = '*';
$app_secret = '*';

class MyLogger {
  public function log( $msg ) {
    print_r( $msg . "<br />" );
  }
}
$pusher = new Pusher($app_key, $app_secret, $app_id);
$logger = new MyLogger();
$pusher->set_logger( $logger );
$data['message'] = 'hello world';
$result = $pusher->trigger('test_channel', 'my_event', array( 'hello' => 'world' ));
$logger->log( "---- My Result ---" );
$logger->log( $result );`
```

And the answer I have is:

`Pusher: ->trigger received string channel "test_channel". Converting to array.
Pusher: create_curl( http://api.pusherapp.com:80/apps/*/events?auth_key=*&auth_signature=*&auth_timestamp=*&auth_version=1.0&body_md5=*)
Pusher: trigger POST: {"name":"my_event","data":"{\"hello\":\"world\"}","channels":["test_channel"]}
Pusher: exec_curl response: Array ( [body] => Unknown auth_key [status] => 400 ) 
---- My Result ---`

What am I doing wrong?

What I want is to send notifications from the server.

**Comment by manoj-matrixesol** [comment]
IU am also having the same problem. Anybody out there who can shed some light in this???

**Comment by manoj-matrixesol** [comment]
Its working when I pass options parameters in it.


```
$options = array(
    'cluster' => 'ap1',
    'encrypted' => true
  );


$pusher = new Pusher($app_key, $app_secret, $app_id, $options);
```
