### ISSUE TITLE
StyleCI Not Enabled Anymore

### ISSUE THREAD

**Issue by GrahamCampbell** [pusher/pusher-http-php#121]
StyleCI requires the connected user to be an admin on the repo. The connected user is not an admin anymore so StyleCI has disabled itself.

**Comment by GrahamCampbell** [comment]
Infact, the connected user didn't even have push access anymore.

**Comment by luismfonseca** [comment]
Well, I've added it back but there was probably not much love for the StyleCI results are there are many things that it is complaining about... Or maybe I'm missing something...

I don't know, maybe I should review the suggestions (most of them just seem to be to replace `array` with `[]` but I don't know if the project supports pre PHP-5.4 versions).

**Comment by GrahamCampbell** [comment]
The idea with StyleCI is you always have it passing. If it's changing loads of things you don't want, then you'll need to modify the config until it does what you want, that way you can get the most out of it's ability to automatically push cs fixes to your code.

**Comment by luismfonseca** [comment]
Ok, sounds interesting.
Thanks for pointing this out Graham. Just recently I've become the owner for this project and that's why I need to review this integration.

**Comment by luismfonseca** [comment]
Alright, it's working so I'm closing the ticket.

Thanks!
