### ISSUE TITLE
Unable to set curl options

### ISSUE THREAD

**Issue by kdubuc** [pusher/pusher-http-php#127]
When I provide curl_options array in the pusher constructor, the curl is not configured properly.

Actually, the settings array in Pusher is not affected by curl_options because of this line : https://github.com/pusher/pusher-http-php/blob/master/lib/Pusher.php#L147 (curl_options is not defined in the initial declaration of $settings)

Can you confirmed if it is a bug ? Can I PR ?

**Comment by kdubuc** [comment]
I don't see it before but https://github.com/pusher/pusher-http-php/pull/122 is related

**Comment by luismfonseca** [comment]
Ok, I've reviewed and merge the other PR. Thanks for bringing this up.
