### ISSUE TITLE
cURL doesn't work on the Google App Engine environment

### ISSUE THREAD

**Issue by adamyeats** [pusher/pusher-http-php#13]
Via support: "It seems that your php library uses cURL which is not supported on GAE PHP"

On further inspection, it seems this is correct. If we want to support this platform, `urlfetch` might be a better solution.

**Comment by Prefinem** [comment]
@ajessup while I can see streams being very useful, I can't help but fully agree with @mtdowling on this. In so many of my projects, I find using cURL much more enjoyable, flexible and powerful not to mention the huge list of libraries that already rely on cURL

**Comment by mtdowling** [comment]
It should also be noted that the Google App Engine stream wrapper implementation doesn't appear to support using a custom CA bundle (or any ssl context option other than "verify_peer"): https://cloud.google.com/appengine/docs/php/urlfetch/

> There are a few considerations to keep in mind when using these wrappers in your Google App Engine application:

> - When connecting to web sites using HTTPS, the default behavior is to validate the certificate of the host and reject requests where the vertificate does not match. This is the opposite to the default behavior of PHP, and to change this behavior you can set the value of verify_peer to false in the ssl section of the context parameters.
- All other values of ssl contexts options are ignored.

This makes an even stronger case for adding cURL support. But even if support cURL is added, the other ssl context options should be supported.

**Comment by dvhirst** [comment]
Folks, this issue has caused me to stop my work to implement CiviCRM /
WordPress on GAE.  I've spent the past couple of days (not weeks and
months) implementing the same (actually newer and better) configuration on
Amazon Web Services, and it has gone very smoothly so far.  I'd really
rather be on Google, but it just hasn't worked.  FWIW, YMMV.

Regards,

Don Hirst

**Comment by Neira1991** [comment]
I am developing a mobile app on Google app engine, and it has been difficult to implement gcm, the community recommends "urlfetch" but will that urlfetch can replace curl to gcm on Google App engine?

**Comment by dvhirst** [comment]
Another six months have passed with no action on this topic.  Is Google going to address cURL or not?

**Comment by Prefinem** [comment]
cURL is now allowed on GAE.  In your app.yaml file you need this:

    runtime: php55

Then you will need to create a php.ini file in your root directory with the line

    extension = "curl.so"

**Comment by dvhirst** [comment]
Thanks for this information.  I'll follow up on it.

**Comment by Prefinem** [comment]
Yup, no worries.  Just a heads up. After enabling the billing, it will take a bit for it to be activated.  I usually wait an hour or so before testing it.

**Comment by scripthead** [comment]
This still doesn't seem to work. I have billing enabled on the project and the following in app.yaml
```
runtime: php55
```
and this in php.ini
```
extension = "curl.so"
```
and the script 

```
$ch = curl_init('http://google.com/');
$response = curl_exec($ch);
echo '<pre>' . print_r(curl_getinfo($ch),1);
echo '<pre>' . print_r(curl_error($ch),1);
echo '<pre>' . print_r($response,1);
die;
```
but it produces the following output:

```
Array
(
    [url] => http://google.com/
    [content_type] => 
    [http_code] => 0
    [header_size] => 0
    [request_size] => 0
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0
    [namelookup_time] => 0.047984
    [connect_time] => 0
    [pretransfer_time] => 0
    [size_upload] => 0
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 0
    [download_content_length] => -1
    [upload_content_length] => -1
    [starttransfer_time] => 0
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 
    [certinfo] => Array
        (
        )

    [primary_port] => 0
    [local_ip] => 
    [local_port] => 0
)
```

notice the content type and http code are empty. On a local environment the same code produces

```
Array
(
    [url] => http://google.com/
    [content_type] => text/html; charset=UTF-8
    [http_code] => 302
    [header_size] => 234
    [request_size] => 49
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.157038
    [namelookup_time] => 0.068574
    [connect_time] => 0.112838
    [pretransfer_time] => 0.112901
    [size_upload] => 0
    [size_download] => 262
    [speed_download] => 1668
    [speed_upload] => 0
    [download_content_length] => 262
    [upload_content_length] => 0
    [starttransfer_time] => 0.156984
    [redirect_time] => 0
    [redirect_url] => http://www.google.com.ua/?gfe_rd=cr&ei=CnMNVuyVAqWG8Qe0pJLICQ
    [primary_ip] => 173.194.112.14
    [certinfo] => Array
        (
        )

    [primary_port] => 80
    [local_ip] => 192.168.0.3
    [local_port] => 53909
)
```

**Comment by Prefinem** [comment]
Did you set a billing limit?

**Comment by scripthead** [comment]
I have billing limited to $50/day and haven't used over $2 in the last week.

**Comment by Prefinem** [comment]
http://terrenceryan.com/blog/index.php/php-on-app-engine-does-curl/

> cURL is limited by the restrictions of App Engine’s sockets but include:
> * **Limited from targeting Google domains**
> * May be reclaimed after 2 minutes of inactivity

Try calling a different domain instead of Google

**Comment by scripthead** [comment]
That did it! Thank you.

**Comment by Prefinem** [comment]
No problem!
