### ISSUE TITLE
Addition of namespace breaks Laravel integration (Error: Class Pusher not found)

### ISSUE THREAD

**Issue by kn100** [pusher/pusher-http-php#145]
Since Laravel (Specifically Illuminate Broadcaster) tightly couples with this integration library, it is referring to Pusher without taking into account the introduction of a namespace.

The simplest workaround is simply change the references so that they are correct - a user has created an automation for this task here: https://stackoverflow.com/questions/45052853/class-pusher-not-found

Another workaround is just to continue using the previous version of this lib until Laravel update their end.

**Comment by luismfonseca** [comment]
This is a good point, I wonder if Laravel 5.5 - which is about to be released -, will have this fixed.

If not, I'm not sure what to do. We could suggest using the v2 version while the Illuminate Broadcaster isn't updated...

**Comment by kn100** [comment]
Closed as issue is with Laravel.
