### ISSUE TITLE
Pusher class not found

### ISSUE THREAD

**Issue by cdjohnnatha** [pusher/pusher-http-php#146]
I realized that with the new version of Pusher (3) it's changed the namespace for Pusher\Pusher and it's not updated in Broadcasts classes.... I solved and answered here: https://stackoverflow.com/questions/45052853/class-pusher-not-found/45325814#45325814

**Comment by Dimimo** [comment]
Same here. I've re-winded to ^2.6 and ran `composer update --no-scripts` as it's not a good idea to change any vendor script. Laravel/Internals may come with a solution but I doubt it.

**Comment by cdjohnnatha** [comment]
Hello, I solved it changing some stuffs,

I already answered here: https://stackoverflow.com/questions/45052853/class-pusher-not-found/45325814#45325814

**Comment by Dimimo** [comment]
@cdjohnnatha I saw your workaround and it does work on the testserver. Thanks for your suggestion. On the production I still run on ^2.6 and wait for a laravel solution. Changing the namespace to Pusher/Pusher makes sense, but it can break tightly connected classes.

**Comment by cdjohnnatha** [comment]
But it's just instantiating the necessary but I think that they forgot to update just those files or something like that. Let's wait :D

**Comment by thalisvilela** [comment]
Hello folks! Any permanent solution for this issue?

**Comment by dj3plles** [comment]
@Dimimo I tried what you commented above now I am getting a new error. Says **BroadcastException in PusherBroadcaster.php** (line 106). What am I doing wrong?

**Comment by kn100** [comment]
Closing as this was an issue in Laravel, not here. Thanks for reporting it though!
