### ISSUE TITLE
Implement user info per presence-chanel

### ISSUE THREAD

**Issue by augusto3691** [pusher/pusher-http-php#151]
can u guys implement the feature of having users info as described in http API documentation?

[link to api documentation](https://pusher.com/docs/rest_api#users)

i cant find this anywhere

**Comment by WillSewell** [comment]
I agree that this library should support this. For now you can achieve this with

```php
$response = $pusher->get('/channels/presence-channel-name/users');
if( $response[ 'status'] == 200 ) {
  // convert to associative array for easier consumption
  $users = json_decode( $response[ 'body' ], true )[ 'users' ];
}
```

It's documented in https://pusher.com/docs/server_api_guide/interact_rest_api#presence-users

**Comment by WillSewell** [comment]
Implemented in https://github.com/pusher/pusher-http-php/pull/209.
