### ISSUE TITLE
Merge new-lib branch

### ISSUE THREAD

**Issue by WillSewell** [pusher/pusher-http-php#152]
@zimbatm made a start on a new version of the pusher-http-php library (https://github.com/pusher/pusher-http-php/tree/new-lib) and the branch has a fair amount of people using it, notably because it lets people specify the host / cluster that they want to publish to, which the current version (on master) did not let you do for some time. That's not the only improvement though. 

We should decide what we want to do with the new-lib branch and potentially make it the new version of the library on master, and release a new version.

**Comment by kn100** [comment]
I haven't looked at this branch in detail, but it seems like it is now a fair bit behind Master. Is there anything in particular that it does better than the current state of master?

**Comment by WillSewell** [comment]
I'm not sure what the main features are beyond cluster selection. It looks like a bunch of tests were added judging by the commits. Maybe @zimbatm or @tanuck could elaborate.

It might make more sense to just add cluster selection support to master for now.

**Comment by zimbatm** [comment]
If I remember correctly the main thing was the pluggable HTTP client. The library on master is depending on libcurl which is not available everywhere (eg: App Engine). The PHP builtins library is also pretty good now(?) and can use different concurrency models.

**Comment by WillSewell** [comment]
Thanks! It sounds like the right approach would be to modernise the existing master (instead of merging this branch) then.

**Comment by WillSewell** [comment]
Closing because we would rather add specific requested features from new-lib to master on a case-by-case basis rather than merging new-lib at this point.

I'll create a specific issue to track the interest in supporting a pluggable HTTP client.
