### ISSUE TITLE
Log Level is not defined with Monolog

### ISSUE THREAD

**Issue by rafaeltovar** [pusher/pusher-http-php#157]
We use Monolog for my Logger implementation in my app. When I set the logger in Pusher client we obtain this error:

"Exception: Level "Pusher: INFO: create_curl( https://api-eu.pusher.com:443/apps/*****************&auth_version=1.0&body_md5=************* )" is not defined, use one of: 100, 200, 250, 300, 400, 500, 550, 600 [] []"

Monolog implements Psr `LoggerInterface`  [1] with next `log` method:

```php
    /**
     * Logs with an arbitrary level.
     *
     * @param mixed  $level
     * @param string $message
     * @param array  $context
     *
     * @return void
     */
    public function log($level, $message, array $context = array());
```
[1] https://github.com/php-fig/log/blob/master/Psr/Log/LoggerInterface.php

But Pusher client use incorrectly `log` method, without `$level` parameter.

```php
    /**
     * Set a logger to be informed of internal log messages.
     *
     * @return void
     */
    public function set_logger($logger)
    {
        $this->logger = $logger;
    }
    /**
     * Log a string.
     *
     * @param string $msg The message to log
     *
     * @return void
     */
    private function log($msg)
    {
        if (is_null($this->logger) === false) {
            $this->logger->log('Pusher: '.$msg);
        }
    }
```

**Comment by rafaeltovar** [comment]
A quick and shitty solution is write a wrapper for encapsulate the `Psr\Log\LoggerInterface`.

```php
use Psr\Log\LoggerInterface;

class PsrToPusherLogger {
    protected $defaultLevel;
    protected $logger;

    public function __construct(LoggerInterface $logger, $defaultLevel = 100) {
        $this->logger = $logger;
        $this->defaultLevel = $defaultLevel;
    }

    public function log($message) {
        $this->logger->log($this->defaultLevel, $message);
    }
}
```

For use this solution:

```php
use Monolog\Logger;

// ...

$pusher->set_logger(new PsrToPusherLogger($logger, Logger::INFO));
```

**Comment by kn100** [comment]
We don't implement the logger in this fashion initially, however now that PSR-3-logger entered into the accepted state, it is probably time that we did. I'll look into modifying this library to officially support this logging interface. Thanks for the report!
