### ISSUE TITLE
Consider refactoring logging to use PSR-3

### ISSUE THREAD

**Issue by adamthehutt** [pusher/pusher-http-php#18]
The logging functionality is useful but pretty crude. Most importantly, there's no distinction between  "log levels". It would be helpful, for example, to distinguish between basic informational event logging and error conditions (such as a failed trigger()). 

The best way to do this would be by requiring that the $pusher->logger object implements the LoggerInterface specified in PSR-3:
http://www.php-fig.org/psr/psr-3/

If you're open to this it's quite easy to do and I'd be happy to provide a pull request.

Thanks,
Adam

**Comment by RobinvdVleuten** [comment]
Any progress on this issue? Would be great to have this feature for better integration with for example Symfony

**Comment by leggetter** [comment]
The likelihood is that if we're going to do any work on a more compliant library it'll happen in the [new-lib branch](https://github.com/pusher/pusher-http-php/tree/new-lib).

No work on this is scheduled right now. We do plan to do some additional hiring to increase our capacity to invest in updating some of our libraries. But I don't have any ETA on that.

**Comment by RobinvdVleuten** [comment]
@leggetter Is it possible to add such functionality through a PR?

**Comment by leggetter** [comment]
@RobinvdVleuten A PR would be great with a proviso that the plan for this branch is to keep it working with PHP 5.2. So no namespaces. The logger can thus align with the logger interface, but I don't think it'll be able to import and reference the PSR-3 definition.

Does that make sense?

The new-lib branch won't have such a restriction. The main work left with the new-lib branch is to ensure that the API is similar to this branch. But with updated conventions e.g. `get_channel_info` becomes `getChannelInfo`. I'm also very keen to port the tests from this branch over to ensure that.

**Comment by RobinvdVleuten** [comment]
@leggetter I understand the point about PHP 5.2. But since you're working on a new version, I guess it's a better idea to create a PR for the new-lib branch. I'll see what I can do on a short notice :)

**Comment by tanuck** [comment]
Is there any timeframe in mind for this, as well as the 'new-lib' version as a whole?

**Comment by leggetter** [comment]
@tanuck - no timeframe. But we're in the process of recruiting to allow us to be able to give the libraries more attention.

**Comment by tanuck** [comment]
@leggetter Shame. Are you happy with some outsider contributions in the meantime? I'm trying to use the 'new-lib' branch in a new project - but it needs work :(

**Comment by leggetter** [comment]
Closing since PRs are being made against the new-lib branch. :+1:
