### ISSUE TITLE
Symfony issue with pusher recipe

### ISSUE THREAD

**Issue by lpj145** [pusher/pusher-http-php#187]
Hi guys, god job, when i try connect with recipe to symfony, pusher api say "unknow auth key", i think because recipe cannot receive a cluster region to login, i'm try without recipe and works right, please review this recipe and test it.

**Comment by WillSewell** [comment]
Hi, could you please post the code which reproduces this problem?

**Comment by WillSewell** [comment]
Unable to reproduce, closing.
