### ISSUE TITLE
Fatal error: Uncaught Error: Using $this when not in object context in D:\upload\test\vendor\pusher\pusher-php-server\src\Pusher.php:490 Stack trace: #0 D:\upload\test\app\Controllers\HomeController.php(104): Pusher\Pusher::trigger(Array, 'my-event', Array) #1

### ISSUE THREAD

**Issue by sahamnadeem** [pusher/pusher-http-php#192]
i just wrote this 
`$options = array(
		    'cluster' => 'ap2',
		    'useTLS' => true
		);
		$pusher = new Pusher\Pusher(
		    '4b7d8404f0f10b8ba41e',
		    '6d22ef03078117629e9b',
		    '616185',
		    $options
		);

		$data['message'] = 'hello world';
		$pusher->trigger('my-channel', 'my-event', $data);`

and havint this error 
`
Fatal error: Uncaught Error: Using $this when not in object context in D:\upload\test\vendor\pusher\pusher-php-server\src\Pusher.php:490 Stack trace: #0 D:\upload\test\app\Controllers\HomeController.php(104): Pusher\Pusher::trigger(Array, 'my-event', Array) #1 D:\upload\test\index.php(14): HomeController::json(Array, Array) #2 {main} thrown in D:\upload\test\vendor\pusher\pusher-php-server\src\Pusher.php on line 490`

what should i do for that?

**Comment by WillSewell** [comment]
That does seem like an odd error. Could you send me the full PHP file that I can run which will reproduce this problem?

Also, could you tell me which version of the library you are using?

**Comment by WillSewell** [comment]
Please contact [Pusher support](https://support.pusher.com/hc/en-us) if this problem persists.
