### ISSUE TITLE
Pusher Beams Support

### ISSUE THREAD

**Issue by pushpinderbagga** [pusher/pusher-http-php#193]
Hi there, I just wanted to check if this library supports the Pusher Beams update coming at the end of this year?

**Comment by pushpinderbagga** [comment]
Here is the update from their website https://pusher.com/docs/push_notifications/migration

**Comment by WillSewell** [comment]
Hi, this already exists as a separate library: https://github.com/pusher/push-notifications-php

**Comment by pushpinderbagga** [comment]
Thanks.
