### ISSUE TITLE
triggerBatch without a socket_id throws `Undefined index: socket_id` after upgrading from 3.2.0 to 3.3.0

### ISSUE THREAD

**Issue by vbarbarosh** [pusher/pusher-http-php#200]
I got the following error after updating from 3.2.0 to 3.3.0

       ErrorException  : Undefined index: socket_id

      at .../vendor/pusher/pusher-php-server/src/Pusher.php:576
        572|     public function triggerBatch($batch = array(), $debug = false, $already_encoded = false)
        573|     {
        574|         foreach ($batch as $key => $event) {
        575|             $this->validate_channel($event['channel']);
      > 576|             $this->validate_socket_id($event['socket_id']);
        577| 
        578|             $data = $event['data'];
        579|             if (!is_string($data)) {
        580|                 $data = $already_encoded ? $data : json_encode($data);

      Exception trace:

      1   Raven_Breadcrumbs_ErrorHandler::handleError("Undefined index: socket_id", ".../vendor/pusher/pusher-php-server/src/Pusher.php", [])
          .../vendor/pusher/pusher-php-server/src/Pusher.php:576

      2   Pusher\Pusher::triggerBatch()
          .../app/Console/Commands/xxx.php:54

      Please use the argument -v to see more details.

[Documentation](https://pusher.com/docs/server_api_guide/interact_rest_api) says that `socket_id` is optional.

**Comment by jameshfisher** [comment]
@vbarbarosh thanks for the report! We'll triage this one and try to get a fix out soon.
