### ISSUE TITLE
Drop PHP 5.x Support

### ISSUE THREAD

**Issue by WillSewell** [pusher/pusher-http-php#206]
Motivation:

* PHP no longer supports this version as of 2019-01-01 (http://php.net/supported-versions.php)
* We currently get the warning when installing dependencies:

  ```
  Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
  ```

  This is because `phpunit/phpunit-mock-objects` was [merged into `phpunit/phpunit`](https://github.com/sebastianbergmann/phpunit/commit/35dcfdc6d1196e32629d5c76d3ee8b0a0093065e#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780). However we cannot upgrade to a version of `phpunit/phpunit` that includes this (>=7.2.0) because it does not support PHP 5.6.

* We have to use an old version of libsodium (1.0.7) for similar reasons.

**Comment by jameshfisher** [comment]
Seems sensible. Let's establish the formal policy that “our PHP support policy is tied to https://php.net/supported-versions.php”, and add that to the README.
