### ISSUE TITLE
chatkit getUsers method throw 500 server error when user not available

### ISSUE THREAD

**Issue by hossammohammed72** [pusher/pusher-http-php#219]
I was trying to use the method 
$chatkit->getUsers();
to check if users existed or not. when users doen't exist it throws out 500 server error, I think it can just return an empty array that would be much better. you're doing a great work keep it up

**Comment by WillSewell** [comment]
Hi, this relates to the chatkit library https://github.com/pusher/chatkit-server-php. Could you please create the issue there?

**Comment by hossammohammed72** [comment]
OK I put it there
