### ISSUE TITLE
Provide a way to asynchronously trigger events

### ISSUE THREAD

**Issue by leggetter** [pusher/pusher-http-php#22]
This is an issue to keep track of the demand for triggering event asynchronously.

There are a couple of pull requests to add this functionality but neither provide any tests. See #4 and #11.

We're looking at sorting out a number of libraries so I'm cleaning out some older issues.

**Comment by mikep2** [comment]
This would be super useful, as triggering events inline presents a serious scaling issue.

Has anyone come up with a successful implementation of a trigger_async method for the php client library, or is there a reason this was not possible?

**Comment by rvanlaak** [comment]
Would be preferable to start using Guzzle here, as proposed in #95 

Note: the Guzzle client to be used should be passable via the constructor as optional argument, so everyone can keep using their Guzzle middleware.

**Comment by elverkilde** [comment]
Pinning this to keep stalebot from closing it. This can now be implemented easily with Guzzle.
