### ISSUE TITLE
Using multiple clusters within an app

### ISSUE THREAD

**Issue by jamesgraham** [pusher/pusher-http-php#220]
Has anyone successfully used multiple clusters to server different users? e.g. a user in the UK is tied to the eu cluster, a user in Japan is tied to the JP one...

Are there any downsides to this?

**Comment by WillSewell** [comment]
This is possible, but you will have to define a Pusher Channels app in each cluster, and publish the same message to each of them. Please [get in touch with support](https://support.pusher.com/hc/en-us) if you want more guidance on how to do this.
