### ISSUE TITLE
triggerBatch returns false for second call

### ISSUE THREAD

**Issue by labeebahmad201** [pusher/pusher-http-php#225]
I am sending notification from laravel queue like this.  Batch contains more than 10 notifications. using array_chunk I create subarray having no more than 10 elements in each subarray.

$pusher->triggerBatch() returns true for first call but for subsequent call it returns false.  
Why is that?

        $chunks_array = array_chunk( $batch, 10, true );
        
            
        $pusher = new \Pusher\Pusher( config('broadcasting.connections.pusher.key'), config('broadcasting.connections.pusher.secret'), config('broadcasting.connections.pusher.app_id'), array( 'cluster' => config('broadcasting.connections.pusher.options.cluster') ) );
        
        foreach( $chunks_array as $mini_batch ){
            $resp = $pusher->triggerBatch( $mini_batch );            
        }

**Update:**

Going through source code I found out that I am getting "Expected request parameter batch to be an array" with 400 status code. What could be the reason?

**Comment by labeebahmad201** [comment]
@WillSewell @hossammohammed72 please have a look.

**Comment by damdo** [comment]
@labeebahmad201 thank you for reporting this, could you please try and set your `$preserve_keys`'s `array_chunk` parameter (your third in this case) to `false` instead of `true`?

Something like:
```
$chunks_array = array_chunk( $batch, 10, false );
```

Let us know if this solves it for you?
