### ISSUE TITLE
Methods should return/throw errors instead of `false`

### ISSUE THREAD

**Issue by syrsly** [pusher/pusher-http-php#229]
Pusher->Get() function returns false if anything other than status of 200. This should be changed into a setting-controlled return value so we can better debug problems without having to edit the library. I suggest using a "verbose" true/false setting and defaulting to false.

**Comment by joshmaines** [comment]
Of course, the debug setting could also be used for this functionality. I don't see why a verbose setting on top of that would be necessary. Anyway, the fact remains, I had to edit the class itself to output this error. People should not be expected to do that since there's a debug option.

**Comment by WillSewell** [comment]
I agree that more detailed information should be thrown from this method by default. However that would involve a breaking change, so it's unlikely to be a change we would make soon.

Out of curiosity, have you configured the SDK with a logger? https://github.com/pusher/pusher-http-php/#debugging--logging. This would have printed the reason for the request failure.

**Comment by joshmaines** [comment]
Yes, I use a custom logger. It was a saving grace in this scenario.

**Comment by WillSewell** [comment]
Ok, that's good it helped. I'm going to rename this issue because I think the root problem is that the methods don't throw/return anything that indicates an error occurred.

**Comment by WillSewell** [comment]
I would like to update the methods to throw exceptions. This is what the Stripe SDK does and I think it's idiomatic. https://stripe.com/docs/api/errors/handling?lang=php
