### ISSUE TITLE
SHA256 appears to be unsupported

### ISSUE THREAD

**Issue by logan-jobzmall** [pusher/pusher-http-php#230]
Hi,

We seem to be getting an intermittent error (only within the past few days) stating that `SHA256 appears to be unsupported - make sure you have support for it.` -- 

We are running PHP 7.2 (Amazon Linux) and Laravel 5.8. When going into Laravel's `php artisan tinker` command and printing hash_algos(), SHA256 comes back within the list. I am not sure why Pusher is having a hard time reading in the values that seem to be there.

According to our lock file, we are using version **4.0.0** of pusher-php-server

Here is a printout of hash_algos():

```
     "md2",
     "md4",
     "md5",
     "sha1",
     "sha224",
     "sha256",
     "sha384",
     "sha512/224",
     "sha512/256",
     "sha512",
     "sha3-224",
     "sha3-256",
     "sha3-384",
     "sha3-512",
     "ripemd128",
     "ripemd160",
     "ripemd256",
     "ripemd320",
     "whirlpool",
     "tiger128,3",
     "tiger160,3",
     "tiger192,3",
     "tiger128,4",
     "tiger160,4",
     "tiger192,4",
     "snefru",
     "snefru256",
     "gost",
     "gost-crypto",
     "adler32",
     "crc32",
     "crc32b",
     "fnv132",
     "fnv1a32",
     "fnv164",
     "fnv1a64",
     "joaat",
     "haval128,3",
     "haval160,3",
     "haval192,3",
     "haval224,3",
     "haval256,3",
     "haval128,4",
     "haval160,4",
     "haval192,4",
     "haval224,4",
     "haval256,4",
     "haval128,5",
     "haval160,5",
     "haval192,5",
     "haval224,5",
     "haval256,5",

```

Any ideas on what would be causing this? It seems like a reboot of our amazon box temporarily fixes this, but the intermittency is very bothersome. 

I also opened this on [Laravel's github](https://github.com/laravel/framework/issues/29691) as well just in case it is an initialization issue on that end.

**Comment by WillSewell** [comment]
This is very odd. If `hash_algos()` really is occasionally returning an empty array, then it must be a problem with the underlying platform (either PHP runtime or Laravel). I'm going to close the issue here because I don't think there's much we can do in the Pusher SDK if `hash_algos()` is returning inconsistent results.
