### ISSUE TITLE
Triggering to multiple channels fails when useTLS: true

### ISSUE THREAD

**Issue by marcaaron** [pusher/pusher-http-php#231]
Spent some time trying to wrap my head around why calls to `trigger()` with multiple channels are failing. I noticed that if a _channel_ is encrypted a `PusherException` will throw...
https://github.com/pusher/pusher-http-php/blob/78a05cceb9d475705241731665b98bfb8f66adfe/src/Pusher.php#L507-L516

Of course, if none of the channels are encrypted (they are not prefixed with `private-encrypted`) then this will proceed fine.

We are experiencing that when `useTLS` is set to `true` that the curl response returns: 
```php
[
    'body' => false, 
    'status' => 0
]
```

However, when `useTLS` is set to `false` it will send to multiple channels without issue.

Is this the expected behavior?

If so, it might be worth adding a check to see whether this option has been set and also throwing in that case?

If not, then any insights into what else we could be doing wrong here?

**Comment by WillSewell** [comment]
I suspect this is unrelated to the logic for handling `private-encrypted-` channels.

Could you initialize the SDK with with a logger, as described in https://github.com/pusher/pusher-http-php#debugging--logging? This will print out the error when the requests is made to Pusher Channels.

**Comment by joshmaines** [comment]
I noticed my test environment wasn't reaching the Pusher console on Pusher's website, so I came here. @WillSewell suggested using a custom logger to figure out the solution, so I did that and noticed I was getting denied by the server because my server's time was 10 minutes behind. Changing the time to the current actual time fixed the problem I was experiencing.

**Comment by elverkilde** [comment]
I'm going to close this issue, as there hasn't been any activity for a long time now. Please feel free to re-open if you are still having problems.
