### ISSUE TITLE
Autoloader bug breaking Yii 1.x installs

### ISSUE THREAD

**Issue by paragonie-scott** [pusher/pusher-http-php#237]
https://github.com/paragonie/sodium_compat/issues/105

This is a weird one. I figured I'd open an issue here so the Pusher devs are aware of it in case there's a quick fix on your end.

**Comment by elverkilde** [comment]
@paragonie-scott is still relevant? I see the issues have been closed.

**Comment by paragonie-scott** [comment]
No, it was fixed upstream.
