### ISSUE TITLE
ErrorException: Trying to access array offset on value of type bool in .../vendor/pusher/pusher-php-server/src/Pusher.php:658

### ISSUE THREAD

**Issue by bigperson** [pusher/pusher-http-php#247]
php 7.4
"pusher/pusher-php-server": "^4.1",

ErrorException: Trying to access array offset on value of type bool in .../vendor/pusher/pusher-php-server/src/Pusher.php:658
--

**Comment by mdpye** [comment]
Fixed via #251 and release 4.1.4
