### ISSUE TITLE
Error  Encountered while trying to install pusher in php version 7.4.1 through composer

### ISSUE THREAD

**Issue by PeterNdeke** [pusher/pusher-http-php#249]
Problem 1
    - Installation request for pusher/pusher-php-server v3.4.1 -> satisfiable by pusher/pusher-php-server[v3.4.1].
    - pusher/pusher-php-server v3.4.1 requires php >=5.4 <7.4 -> your PHP version (7.4.1) does not satisfy that requirement. 

That's the error output i got while trying to install pusher in my php 7.4.1  server. Please kindly assist me, Thanks

**Comment by GrahamCampbell** [comment]
v3 doesn't support PHP 7.4. v4 is needed.

**Comment by GrahamCampbell** [comment]
4.1.1 or higher, specifically.

**Comment by PeterNdeke** [comment]
PHP 7.4.1
Pusher 3.4.1

**Comment by GrahamCampbell** [comment]
Yeh, you need Pusher 4.1.1 or higher...

**Comment by GrahamCampbell** [comment]
The composer error is telling you that 3.4.1 is not compatible with PHP 7.4.

**Comment by mdpye** [comment]
Closing this issue, as the problem has been identified (thank you @GrahamCampbell)

A bug-fix release was made for PHP 7.4 today, so I'd now recommend using pusher-php-server v4.1.4.

**Comment by Campero9813** [comment]
Hello, could you help me solve the same problem, I have not been able to achieve it, please I need your help
