### ISSUE TITLE
Problem installing pusher using composer in laravel, 

### ISSUE THREAD

**Issue by PeterNdeke** [pusher/pusher-http-php#255]
My PHP version is 7.4.1 and while trying to install pusher using composer on my laravel app, i got the following errors

Problem 1
    - pusher/pusher-php-server v4.1.0 requires php >=7.1 <7.4 -> your PHP version (7.4.1) does not satisfy that requirement.
    - pusher/pusher-php-server v4.0.0 requires php >=7.1 <7.4 -> your PHP version (7.4.1) does not satisfy that requirement.
    - Conclusion: remove nahid/talk v2.2.2
    - Conclusion: don't install nahid/talk v2.2.2
    - Conclusion: don't install pusher/pusher-php-server v4.1.4
    - Conclusion: don't install pusher/pusher-php-server v4.1.3
    - Installation request for nahid/talk (locked at v2.2.2, required as ^2.2) -> satisfiable by nahid/talk[v2.2.2].
    - Conclusion: don't install pusher/pusher-php-server v4.1.2
    - nahid/talk v2.2.2 requires pusher/pusher-php-server ^3.0 -> satisfiable by pusher/pusher-php-server[3.4.x-dev, 3.0.x-dev].
    - Can only install one of: pusher/pusher-php-server[v4.1.1, 3.4.x-dev].
    - Can only install one of: pusher/pusher-php-server[v4.1.1, 3.0.x-dev].
    - Installation request for pusher/pusher-php-server ~4.0 -> satisfiable by pusher/pusher-php-server[v4.0.0, v4.1.0, v4.1.1, v4.1.2, v4.1.3, v4.1.4].

**Comment by akeebismail** [comment]
As anyone finds a solution to this ? 
 Problem 1
    - Installation request for pusher/pusher-php-server v4.0.0 -> satisfiable by pusher/pusher-php-server[v4.0.0].
    - pusher/pusher-php-server v4.0.0 requires php >=7.1 <7.4 -> your PHP version (7.4.4) does not satisfy that requirement.

**Comment by GrahamCampbell** [comment]
Probably you used `4.1` instead of `^4.1` for the version constraint, which would cause this error.

**Comment by GrahamCampbell** [comment]
> Installation request for pusher/pusher-php-server v4.0.0 

Why are you installing 4.0.0? Use `^4.1` for the version constraint.

**Comment by dinho-afsn** [comment]
Same problem with ^4.1

**Comment by artsur** [comment]
pusher/pusher-php-server v4.1.0 requires php >=7.1 <7.4 -> your PHP version (7.4.6) does not satisfy that requirement

**Comment by artsur** [comment]
with php 7.3.20 
    - Conclusion: don't install pusher/pusher-php-server v4.1.4
    - Conclusion: don't install pusher/pusher-php-server v4.1.3
    - Conclusion: don't install pusher/pusher-php-server v4.1.2
    - Conclusion: don't install pusher/pusher-php-server v4.1.1
    - Conclusion: don't install pusher/pusher-php-server v4.1.0
    - Can only install one of: pusher/pusher-php-server[v4.0.0, 3.4.x-dev].
    - Can only install one of: pusher/pusher-php-server[v4.0.0, 3.4.x-dev].
    - Can only install one of: pusher/pusher-php-server[v4.0.0, 3.4.x-dev].
    - Installation request for pusher/pusher-php-server ^4.0 -> satisfiable by pusher/pusher-php-server[v4.0.0, v4.1.0, v4.1.1, v4.1.2, v4.1.3, v4.1.4].
    - Installation request for pusher/pusher-php-server (locked at 3.4.x-dev, required as ^4.0) -> satisfiable by pusher/pusher-php-server[3.4.x-dev].

I hav tried to "pusher/pusher-php-server": "^4.0" and "pusher/pusher-php-server": "^4.1"
all the same

**Comment by artsur** [comment]
I have found solution:
1) Change php to version lower than 7.4 (7.3 for example)
2) Install or update pusher/pusher-php-server 
3) Return back php 7.4
May be it is not good idea, but working

**Comment by wikichua** [comment]
> I have found solution:
> 
>     1. Change php to version lower than 7.4 (7.3 for example)
> 
>     2. Install or update pusher/pusher-php-server
> 
>     3. Return back php 7.4
>        May be it is not good idea, but working

same tricks i applied. but not ideal solution. i think why not fork this package and update the composer.json to php ^7.4 import it again. it should be working too...

**Comment by MrSmith1010** [comment]
try this

[https://medikre.com/stories/bagaimana-cara-downgrade-php-74-ke-73-di-ubuntu?](url)

**Comment by elverkilde** [comment]
The latest version (currently 5.0.1) supports `^7.1`, including the versions mentioned here. I am going to close this issue assuming it has been resolved in the latest release. Feel free to re-open if you are still having issues.

**Comment by nesyou01** [comment]
``composer require pusher/pusher-php-server ^VERSION --ignore-platform-reqs``
