### ISSUE TITLE
get_channels docblock return annotation incorrect

### ISSUE THREAD

**Issue by ChrisHSandN** [pusher/pusher-http-php#264]
All the methods which return the output of `json_decode($response['body'])` are annotated as `array|bool` e.g. [`get_channels`](https://github.com/pusher/pusher-http-php/blob/251f22602320c1b1aff84798fe74f3f7ee0504a9/src/Pusher.php#L670) `get_users_info()`, `get_channel_info()`

This is incorrect and should be `\stdClass|bool`

Strangely you do convert it to an array inside `Pusher->get()` (which those 3 methods call) but then ignore that array and `json_decode()` it again but this time to an object before returning it 🤔. This leads to an inconsistency of return type depending on whether you use the universal `get()` or the named functions.

**Comment by elverkilde** [comment]
hi @ChrisHSandN, thank you for raising this issue. I would like to fix this, but I am by no means a PHP expert. Can you recommend a tool to check these annotations?

**Comment by elverkilde** [comment]
this was fixed here: https://github.com/pusher/pusher-http-php/commit/3fa43c319368e07d5053445d493152f6377bf7e9

**Comment by ChrisHSandN** [comment]
@elverkilde In response to your question about a tool to find these issues, Jetbrains PHPStorm IDE seems to do a fairly good job of static analysis. As an example, this is an overview of what the 4.1.5 project project checked against PHP 7.3 looks like:

![image](https://user-images.githubusercontent.com/13466620/111128460-d3203e80-856c-11eb-88e4-3b91cd20d47f.png)
