### ISSUE TITLE
Misordered assertEquals arguments

### ISSUE THREAD

**Issue by nerg4l** [pusher/pusher-http-php#272]
The parameter order of `assertEquals` in PHPUnit is the following: `$expected`, `$actual`, `$message`.

The tests defined for this lib are using `$expected`, `$actual` in a switched order.

Examples:

https://github.com/pusher/pusher-http-php/blob/master/tests/unit/authQueryStringTest.php#L17-L21

https://github.com/pusher/pusher-http-php/blob/master/tests/unit/webhookTest.php#L45-L46

**Comment by gileswells** [comment]
Thank you for this. It would appear that you are absolutely right. If you'd like to create a pull request to resolve this I can make sure it gets in front of the engineering team to be reviewed and merged. If not that is fine too and I can add it to our backlog to resolve.

**Comment by nerg4l** [comment]
I will create a PR this afternoon (CET).
