### ISSUE TITLE
error array_merge - laravel 8 - php74

### ISSUE THREAD

**Issue by marcossaoleo** [pusher/pusher-http-php#278]
Message
array_merge(): Expected parameter 2 to be an array, null given

{
    "class": "ErrorException",
    "message": "array_merge(): Expected parameter 2 to be an array, null given",
    "code": 0,
    "file": "/laravel/vendor/pusher/pusher-php-server/src/Pusher.php:518",

**Comment by ben-pusher** [comment]
You may need to use `composer require pusher/pusher-php-server ^4.1`- support for v5.0.0 of this library hasn't been added to Laravel yet.

**Comment by Koozza** [comment]
@ben-pusher I'm working on a PR for laravel but ran into another issue with 5.0.0. Not sure if you want me to open another Issue for this and / or this is a user error.

I'm receiving a `Undefined property: stdClass::$channels` on Pusher.php line 538. It appears there is no channels in the response body from Pusher.

The contents of the `$response` are:

```
array: 2 [
  " body " => " {} "
  " status " => 200
]
```

Is this a bug with this package, or my own fault?

Code I'm using to test:
```
                $pusher = new Pusher\Pusher( 'xxx', 'xxx', 'xxx', array( 'cluster' => 'eu', 'useTLS' => true ) );
                $pusher->trigger( [ 'channel-1', 'channel-2' ], 'my_event', 'hello world' );
```

**Comment by ben-pusher** [comment]
Channels are returned only when you use the `info` parameter when publishing events - see https://pusher.com/docs/channels/library_auth_reference/rest-api#post-event-trigger-an-event-. 

For example. When using: 
`$pusher->trigger(['my-channel', 'my-channel-2'], 'my-event', $data, array('info' => 'subscription_count'));`
The response is: 

```(
    [channels] => Array
        (
            [my-channel] => stdClass Object
                (
                    [subscription_count] => 0
                )

            [my-channel-2] => stdClass Object
                (
                    [subscription_count] => 0
                )

        )

).

**Comment by Koozza** [comment]
Yeah I just figured that out! Thanks for your response. I've created a PR to solve this issue :) 

https://github.com/pusher/pusher-http-php/pull/281

**Comment by marcossaoleo** [comment]
> Você pode precisar usar `composer require pusher/pusher-php-server ^4.1`- o suporte para v5.0.0 desta biblioteca ainda não foi adicionado ao Laravel.

It worked.
now gave another error:

{
    "class": "Illuminate\\Broadcasting\\BroadcastException",
    "message": "Pusher error: 404 NOT FOUND\n.",
    "code": 0,
    "file": "/laravel/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:122",
    "trace": [

**Comment by ben-pusher** [comment]
This can be caused when the app credentials haven't been set or read correctly. Can you ensure you have set your app ID, key, cluster etc correctly? You should also run `php artisan config:cache` to clear the cache to ensure any changes are picked up.

**Comment by marcossaoleo** [comment]
> php artisan config:cache

Did not work "php artisan config: cache"
Put key, secret and app_id in broadcasting.php it worked

Thanks

**Comment by nausixkiz** [comment]
> You may need to use `composer require pusher/pusher-php-server ^4.1`- support for v5.0.0 of this library hasn't been added to Laravel yet.

Thanks .. It solved my problem

**Comment by nausixkiz** [comment]
> > php artisan config:cache
> 
> Did not work "php artisan config: cache"
> Put key, secret and app_id in broadcasting.php it worked
> 
> Thanks

Try add `'Pusher' => Pusher\Pusher::class`, in `app\config`
It worked

**Comment by Koozza** [comment]
@nausixkiz Small update: 5.x is now supported in Laravel 8.29

**Comment by ben-pusher** [comment]
Great, thanks for notifying us. I'll close this out now.

**Comment by Sergey98Am** [comment]
> You may need to use `composer require pusher/pusher-php-server ^4.1`- support for v5.0.0 of this library hasn't been added to Laravel yet.

Thank you so much

**Comment by ohsnappityph** [comment]
I update my laravel to at 8.29 to enable pusher v5.x compatibility. :*

**Comment by 9896** [comment]
> You may need to use `composer require pusher/pusher-php-server ^4.1`- support for v5.0.0 of this library hasn't been added to Laravel yet.

Thanks, i had spent hours trying to fix this. Your solution worked like a charm

**Comment by bhavinjr** [comment]
> You may need to use `composer require pusher/pusher-php-server ^4.1`- support for v5.0.0 of this library hasn't been added to Laravel yet.

Working fine bro, I was using the latest version but not get success. this one work likes a rocket

**Comment by DaviJP7** [comment]
C:\xampp\htdocs\xcproject\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php comment in line the 'if' condition around line 95

**Comment by wasifiqbal1990** [comment]
> You may need to use `composer require pusher/pusher-php-server ^4.1`- support for v5.0.0 of this library hasn't been added to Laravel yet.

This fixed my issue too thanks.

**Comment by acidjazz** [comment]
> You may need to use `composer require pusher/pusher-php-server ^4.1`- support for v5.0.0 of this library hasn't been added to Laravel yet.

Can we get support for Laravel pleases? I now have to downgrade v7.0.2

**Comment by molina34** [comment]
> You may need to use `composer require pusher/pusher-php-server ^4.1`- support for v5.0.0 of this library hasn't been added to Laravel yet.

This worket for me!!!! thanks!

**Comment by acidjazz** [comment]
> Great, thanks for notifying us. I'll close this out now.

I don't see why a bug that requires you to use an older version should be closed
