### ISSUE TITLE
array_merge gets null param, default should be []

### ISSUE THREAD

**Issue by xlcrr** [pusher/pusher-http-php#286]
Hi, 

Trying to implement v5.0.1 on Laravel v5.8.38

I can receive events on the client from the Pusher dashboard

However, our native events handled by Laravel Horizon / Queue manager fail

```
ErrorException: array_merge(): Expected parameter 2 to be an array, null given in /home/forge/mysite.com/vendor/pusher/pusher-php-server/src/Pusher.php:518

#1 /home/forge/mysite.com/vendor/pusher/pusher-php-server/src/Pusher.php(518): array_merge(Array, NULL)

#2 /home/forge/mysite.com/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php(111): Pusher\Pusher->trigger(Array, 'order.created', Array, NULL, true)

```

I realise this may be a Laravel issue. It seems like the socket param is not being passed through with the broadcast event?

PusherBroadcaster.php

```
    public function broadcast(array $channels, $event, array $payload = [])
    {
        $socket = Arr::pull($payload, 'socket'); // NULL

        $response = $this->pusher->trigger(
            $this->formatChannels($channels), $event, $payload, $socket, true
        );

```

From the failed job payload

```
event: {
    id_order: 1,
    amount: 10,
    socket: null
},
```

**Comment by Koozza** [comment]
This is most likely a laravel issue. I've created a PR for 8.X. But as i recall 5.8 is currently not receiving updates anymore.  So i'd suggest upgrading to 6.x with pusher 4.x or laravel 8.x with pusher 5.x

**Comment by GrahamCampbell** [comment]
Only Laravel 6 and 8 are recieving updates.

**Comment by lisandrop05** [comment]
I had the same problem, PusherBroadcaster on laravel not calling trigger function of Pusher.php with right parameter, in order to get it working I create a workaround that for Now is working for my without changing the laravel PusherBroadcaster here is the link:

#issuecomment-787487210

**Comment by ben-pusher** [comment]
As @Koozza has mentioned, this looks to be a Laravel issue. @lisandrop05 has also shared a workaround where an upgrade in Laravel is not possible. I'll close this off now.
