### ISSUE TITLE
It is Paid..(:

### ISSUE THREAD

**Issue by jignesh87** [pusher/pusher-http-php#30]
Hii.
Pusher is a paid api is there any opensource?

**Comment by leggetter** [comment]
Pusher is a paid service. However, we do have a full feature Sandbox plan which is free for up to 20 simultaneous connections and 100k messages.

If you are looking for a self-hosted version of Pusher you could take a look at:

* https://github.com/stevegraham/slanger
* https://github.com/edgurgel/poxa-erlang
