### ISSUE TITLE
[6.1] `build_auth_query_params()` returns array instead of string

### ISSUE THREAD

**Issue by DarkGhostHunter** [pusher/pusher-http-php#302]
As title says, this [PHPDoc says the function returns a string](https://github.com/pusher/pusher-http-php/blob/master/src/Pusher.php#L276-L299) while it returns an array.

**Comment by elverkilde** [comment]
Thanks for reporting this, we're currently working on a major overhaul here: #304 .

**Comment by DarkGhostHunter** [comment]
Should a hotfix for the current version be made?
