### ISSUE TITLE
What is the new correct way of disabling SSL verification post 6.0?

### ISSUE THREAD

**Issue by vesper8** [pusher/pusher-http-php#313]
Previously we were able to set

```
    'curl_options' => [
        CURLOPT_SSL_VERIFYHOST => 0,
        CURLOPT_SSL_VERIFYPEER => 0,
    ],
```

But since `curl_options` was removed in `6.0`, what is now the current way of disabling SSL verification?

I've found that if I edit `vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php` and add `$options['verify'] = false;` to the `__invoke` method it will do the trick.. but I can't figure out how to set this value through the Laravel configuration.

I know this isn't a Laravel package but it's widely used in Laravel so am hoping someone can provide some insight. Is it even possible or is the only way to revert to `^5.0` ?

Thanks

**Comment by francoism90** [comment]
This is a real problem when just running and testing packages locally. I do understand the importance of signed certificates, but on LAN this has little to no meaning, sometimes you do need to test with SSL-enabled and just use a self-signed certificate.

 Can you please make this configurable again? Or can this be disabled globally? Using a fork is indeed not recommend @vesper8.

**Comment by benw-pusher** [comment]
This library is designed as a library for pushing events to the Pusher Channels service. When using this service there is no need to customise the SSL certificates. 
This request is an enhancement. Unfortunately, updating this library to facilitate the use of a 'Pusher replacement' is not a high priority and it is likely we won't implement this.

**Comment by Hillcow** [comment]
Any news on this? I understand it's not your task, but so many people would benefit from it.

**Comment by francoism90** [comment]
@Hillcow Are you using a framework? It works for me on Laravel 9 with a self-signed cert.

**Comment by Hillcow** [comment]
@francoism90 I'm on Laravel 9 as well, yes. So what's your local setup without setting `CURLOPT_SSL_VERIFYHOST` and 
`CURLOPT_SSL_VERIFYPEER`?

**Comment by francoism90** [comment]
@Hillcow You need to set those options, it will not work without them.

**Comment by Hillcow** [comment]
That is precisely the entire problem of this issue here, @francoism90. Because you cannot set those options after version 5.* of `pusher-http-php`. Check your version, you're probably running on 5.* or even older.

**Comment by francoism90** [comment]
@Hillcow `"pusher/pusher-php-server": "^7.0",`

**Comment by Hillcow** [comment]
@francoism90 How? Did you set `client_options` in `broadcasting.php`? `CURLOPT_SSL_VERIFYHOST` and `CURLOPT_SSL_VERIFYPEER` is definitely not supported any longer.

Did you use [this solution](https://github.com/soketi/soketi/issues/191#issuecomment-1028877964)? Was it actually merged in Laravel 9? Cannot find anything about it in the docs.

**Comment by francoism90** [comment]
@Hillcow https://github.com/soketi/soketi/issues/191#issuecomment-1028877964

Yeah, sorry.. I'm extending this.

However, I no longer need this as I'm using Soketi over localhost (internal), and HTTPS using a nginx proxy to provide the socket publicly.
