### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by seritpt** [pusher/pusher-http-php#318]
Nothing works :-( 
Cant install with composer with many errors
"Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\mad> composer require pusher/pusher-php-server
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: C:\Users\mad\Documents\MEGA\PortableApps\XAMPP\App\xampp\php\ext\pdo_mysql (Imposs├¡vel localizar o m├│dulo especificado.), C:\Users\mad\Documents\MEGA\PortableApps\XAMPP\App\xampp\php\ext\php_pdo_mysql.dll (Imposs├¡vel localizar o procedimento especificado.)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: C:\Users\mad\Documents\MEGA\PortableApps\XAMPP\App\xampp\php\ext\pdo_mysql (Imposs├¡vel localizar o m├│dulo especificado.), C:\Users\mad\Documents\MEGA\PortableApps\XAMPP\App\xampp\php\ext\php_pdo_mysql.dll (Imposs├¡vel localizar o procedimento especificado.)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlite' (tried: C:\Users\mad\Documents\MEGA\PortableApps\XAMPP\App\xampp\php\ext\pdo_sqlite (Imposs├¡vel localizar o m├│dulo especificado.), C:\Users\mad\Documents\MEGA\PortableApps\XAMPP\App\xampp\php\ext\php_pdo_sqlite.dll (Imposs├¡vel localizar o procedimento especificado.)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'pdo_sqlite' (tried: C:\Users\mad\Documents\MEGA\PortableApps\XAMPP\App\xampp\php\ext\pdo_sqlite (Imposs├¡vel localizar o m├│dulo especificado.), C:\Users\mad\Documents\MEGA\PortableApps\XAMPP\App\xampp\php\ext\php_pdo_sqlite.dll (Imposs├¡vel localizar o procedimento especificado.)) in Unknown on line 0
Using version ^7.0 for pusher/pusher-php-server
./composer.json has been updated
Running composer update pusher/pusher-php-server
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
4 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PS C:\Users\mad>"

vendor/autoload.php doens't exist

**Comment by hniehorster** [comment]
Not sure if this is Pusher related... looks more like a issue with your project / composer.
