### ISSUE TITLE
"Pusher\\Pusher::trigger(): Argument #4 ($params) must be of type array, string given

### ISSUE THREAD

**Issue by developer-harismaqsood** [pusher/pusher-http-php#319]
i think this pusher is not working with laravel 7... 
there is any solution..I have fedup from 2 days.

**Comment by benw-pusher** [comment]
You may need to update the version of this library to the latest version - what version are you currently using?

**Comment by benw-pusher** [comment]
Closing as i've had no response. Feel free to reopen if you can provide the version in use.
