### ISSUE TITLE
get_object_vars() error on /src/Pusher.php:459

### ISSUE THREAD

**Issue by ahmadharminto** [pusher/pusher-http-php#322]
Hi, kindly do check this issue

My env :

- php 8.1.2
- laravel 9, using broadcasting channel
- pusher/pusher-php-server ^7.0

Error message :
`local.ERROR: get_object_vars(): Argument #1 ($object) must be of type object, array given {"exception":"[object] (TypeError(code: 0): get_object_vars(): Argument #1 ($object) must be of type object, array given at /<my-project-path>/vendor/pusher/pusher-php-server/src/Pusher.php:459)`

Thank you

**Comment by benjamin-tang-pusher** [comment]
Does this error occur when you call `broadcast(new event(...))->toOthers();`?

**Comment by Attia-Ahmed** [comment]
same issue

**Comment by benjamin-tang-pusher** [comment]
Ahmad, what do you think of Attia's PR? Does it solve your issue?

**Comment by ahmadharminto** [comment]
@benjamin-tang-pusher I think Attia's PR will fix the issue. Thank you.

**Comment by Attia-Ahmed** [comment]
> Ahmad, what do you think of Attia's PR? Does it solve your issue?

Yes it did solve my Issue. for now we are using the forked version in our project and works as expected
