### ISSUE TITLE
pusher throwing "GuzzleHttp\Exception\ConnectException" instead of "BroadcastException" 

### ISSUE THREAD

**Issue by Hillcow** [pusher/pusher-http-php#340]
Shouldn't this pusher package always throw a BroadcastException? Since my upgrade from 4.0 to 6/7 (tried both) I always get a "GuzzleHttp\Exception\ConnectException" when my websockets service is down.

On my local installation I also get a "GuzzleHttp\\Exception\\RequestException" (cURL error 60: SSL certificate problem).

**Comment by benjamin-tang-pusher** [comment]
Hi, our library does not support hosting your own websocket service instead of using our cluster, so I will have to close this issue.
