### ISSUE TITLE
Send events with $.ajax()

### ISSUE THREAD

**Issue by ebrahimpleite** [pusher/pusher-http-php#342]
I can't fire events using jquery's $.ajax({}).

Exemple:
`
$.ajax({
            url: data.post,
            type: "POST",
            data: data,
            dataType: "json",
            beforeSend: function () {
            },
            success: function (response) {
            },
            error: function () {
            }
        });
`

Just using $.post({}).

Exemple:
`
$.post(data.post, {
        data: data
    }, function (response) {}, "json");
`

Is there any method to trigger events with $.ajax({}) as well?

**Comment by benw-pusher** [comment]
Are you encountering a specific error when trying to do this?

**Comment by ebrahimpleite** [comment]
It doesn't return any error as it doesn't send event request to pusher.

**Comment by benw-pusher** [comment]
It may be better to raise a ticket at https://support.pusher.com/hc/en-us/requests/new so you can share the full request being made, including the URL and the authentication setup. 
In general, however, guidance for interacting with the HTTP API directly can be found at https://pusher.com/docs/channels/library_auth_reference/rest-api/.

**Comment by erikn69** [comment]
Maybe `data: {data:data}`
```js
$.ajax({ url: data.post, type: "POST", data: {data:data}, dataType: "json", beforeSend: function () { }, success: function (response) { }, error: function () { } });
```
