### ISSUE TITLE
Left out codes after installation

### ISSUE THREAD

**Issue by bernardarhia** [pusher/pusher-http-php#345]
I installed the pusher package using composer. after installation, some of the methods in the docs are not in the code composer downloaded for me to use. How do I resolve that?

**Comment by benw-pusher** [comment]
Can you share what methods are not available for you to use?

**Comment by benw-pusher** [comment]
We haven't had any update here so I will close this out. If you need further support please get in touch via https://support.pusher.com/hc/en-us/requests/new
