### ISSUE TITLE
No callbacks on private channel. pusher:subscription_error

### ISSUE THREAD

**Issue by brada1703** [pusher/pusher-http-php#346]
Hey everyone,

I had Pusher working fine before updating a few packages. Now I am getting the following error:

`"Error: JSON returned from channel-authorization endpoint was invalid, yet status code was 200. Data was:...`

And

`Pusher :  : ["No callbacks on private.... for pusher:subscription_error"]`

Within the Debug Console, I can see that the channel is disconnecting.

I am using:

- PHP 8.1
- Laravel 9.24.0
- Pusher / Pusher-php-server 7.0.2

My code:

```
import Echo from 'laravel-echo';

window.Pusher = require('pusher-js');

window.Echo = new Echo({
	broadcaster: 'pusher',
	key: process.env.MIX_PUSHER_APP_KEY,
	cluster: process.env.MIX_PUSHER_APP_CLUSTER,
	forceTLS: true
});
```

Is my error here simply due to using PHP8.1? Is it still not supported? If no, does anyone have a work around or do I have to downgrade my app?

**Comment by benw-pusher** [comment]
Hi @brada1703. I believe you raised a support ticket regarding this, but we haven't had a response from you. Are you able to respond there? It would be useful to review the full error message (including the `data` that was included in the error message).

**Comment by brada1703** [comment]
Hi @benw-pusher , Sorry! I just replied to your email :) Thanks!

**Comment by emuter** [comment]
hey @brada1703 . i hope you are doing well.
can you please check on this ...
[https://github.com/pusher/pusher-http-php/issues/348#issuecomment-1267373926](url)

**Comment by benjamin-tang-pusher** [comment]
This was dealt with separately with the Pusher support team.

This was a CORS issue where config/cors.php did not correctly specify the auth endpoint.
