### ISSUE TITLE
Unable to subscribe to private channel - gives 403 | Forbidden

### ISSUE THREAD

**Issue by emuter** [pusher/pusher-http-php#348]

**Comment by benw-pusher** [comment]
Can you provide more info here? 
403 forbidden would indicate that the auth endpoint you have specified requires some form of authentication that is not present in the request being made. Have you checked the setup of your auth server and configured any necessary headers in the client auth request?

**Comment by emuter** [comment]
@benw-pusher i did spend sometime to check on this. but went lazy on to record everything i did.
however, i am at a conclusion that its not a problem with pusher, but with Laravel PusherBroadcaster.php @ auth function

as i have commented this.
//$channelName = $this->normalizeChannelName($request->channel_name);

and gave it directly
$channelName = $request->channel_name;

then everything got resolved.
i do not quite understand why laravel is replacing 'private-' part with a ' ' to continue with private channel authentication. i'd be glad if someone explained that to me or else that got corrected in consideration of it as a bug or any other flaw.

**Comment by benw-pusher** [comment]
HI @emuter. I'm not sure why Laravel is doing this, perhaps you could get some support from Laravel as the code that is causing the error is provided by Laravel and not Pusher.
