### ISSUE TITLE
Echo.listen not working in pusher-php-server 7.2.1

### ISSUE THREAD

**Issue by dobosbalazs** [pusher/pusher-http-php#356]
Hi!

Im using:
- laravel 8.83.25
- laravel-websockets 1.13.1 
- laravel-echo 1.14.0
- pusher-js 7.4.0
with push-php-server.
I had to downgrade push-php-server back to 7.0.2, because Echo.listen is not working in any form. Even /lararvel-websockets built in event tester is not working. No error, response ok, job is done and i can see the message in debug in the browser, but not showing up in the laravel-websockets debugger. Only subscribe is working what you can see it in the debugger too. With the same code everything is fine with 7.0.2 version.

Anyone knows what could be the problem?

Thank you!

**Comment by benw-pusher** [comment]
This is an issue with Laravel Websockets, there is a fix discussed https://github.com/beyondcode/laravel-websockets/pull/1046. 
Our Pusher libraries are designed for compatibility with the official Pusher Channels service and we cannot guarantee compatibility with third party replacements such as Laravel Websockets.

**Comment by dobosbalazs** [comment]
Oh okey, thank you!
