### ISSUE TITLE
Pusher error: cURL error 28: Failed to connect to api-eu.pusher.com port 443: Connection timed out 

### ISSUE THREAD

**Issue by ozgurtr** [pusher/pusher-http-php#359]
When I load test my system, an error like this starts to return. My plan is business.

**Comment by benw-pusher** [comment]
Does your system behave as expected when not load testing your system? 
What cluster are you using?

**Comment by ozgurtr** [comment]
Yes, it works fine when not tested.
We use the eu cluster.

**Comment by ozgurtr** [comment]
![image](https://user-images.githubusercontent.com/113692908/198127620-acc352e2-111a-4444-801c-e45eb8306114.png)
All tested services have a pusher connection.

**Comment by ozgurtr** [comment]
![image](https://user-images.githubusercontent.com/113692908/198128068-d5ec1480-e534-49ab-9f36-9d815b9aa798.png)

**Comment by benw-pusher** [comment]
Thanks for sharing. This may indicate bandwidth / port / process exhaustion on your host service. The EU cluster is handling thousands of requests per second without error. You should double check network performance for your system to ensure this is not contributing.

**Comment by ozgurtr** [comment]
Thank you I will check and give you feedback.

**Comment by benw-pusher** [comment]
We haven't received a response here, so closing off. If you need further support please contact us at https://support.pusher.com/hc/en-us/requests/new
