### ISSUE TITLE
The CI setup is not friendly to community contributors

### ISSUE THREAD

**Issue by stof** [pusher/pusher-http-php#361]
The CI setup currently uses the same jobs to run standalone commands (unit tests, linting) and acceptance tests that require access to secrets. For PRs sent from a fork, secrets are not available (for security reasons) and so the CI marks all jobs as failed due to acceptance tests.

For a better experience, the CI jobs could be split:
- dedicated jobs for acceptance tests (that could be properly marked as skipped rather than failed when secrets are not available)
- jobs for unit tests and linting, that run for all contributions

**Comment by benjamin-tang-pusher** [comment]
Thanks for this suggestion. I will pass to this feedback to our engineering.

I will close this GH issue.
