### ISSUE TITLE
Internal Server Error 500 

### ISSUE THREAD

**Issue by ronskie69** [pusher/pusher-http-php#368]
I did the instructions you have provided but when I look up to the localhost, it's not workign anymore

**Comment by benw-pusher** [comment]
Can you share the instructions you followed and the error being encountered?

**Comment by benw-pusher** [comment]
Hi @ronskie69. We haven't had a response here so I will close this out. If you need further support contact us at https://support.pusher.com/hc/en-us/requests/new
