### ISSUE TITLE
Pusher Presence Channel Data

### ISSUE THREAD

**Issue by krixnaas** [pusher/pusher-http-php#375]
My Pusher Presence channel has all the user data. 
![image](https://github.com/pusher/pusher-http-php/assets/14975723/4b74004d-57ad-4645-b223-590839b4599b)

I am able to access user id 
![image](https://github.com/pusher/pusher-http-php/assets/14975723/ccc84868-a2ad-4a11-ad3a-8451b7ea9692)

Following information below, what are the data I can access other than user id? 
![image](https://github.com/pusher/pusher-http-php/assets/14975723/0a50e775-028b-465b-87d3-72fd3b49f78c)

**Comment by benw-pusher** [comment]
The users endpoint that both `getPresenceUsers` and `get('/channels/presence-channel-name/users');` calls returns the list of User IDs only. See https://pusher.com/docs/channels/library_auth_reference/rest-api/#get-users for detail. 

It is not possible to retrieve the full user object from the query API.
