### ISSUE TITLE
Question about deprecation for all of the versions above v13

### ISSUE THREAD

**Issue by v-trishyn** [pusher/pusher-http-php#377]
Hello
In [this blog](https://pusher.com/blog/websocket-compression-pusher/) Pusher said that all versions below v13 will be deprecated.
This package is not on the deprecation list?

**Comment by benw-pusher** [comment]
This package is not being deprecated - in fact none of our packages are being deprecated. We are only ending support for specific websocket protocols. As the protocol in use is determined by the device (and not our libraries) it is only devices that don't support v13 that will be impacted.
