### ISSUE TITLE
Incompatible with AWS SDK due to paragonie/sodium_compat dependency

### ISSUE THREAD

**Issue by BenSeDev** [pusher/pusher-http-php#392]
Hello, 

I'm unable to install the package due to incompatibility with `paragonie/sodium_compat`.
We're using the AWS php SDK, which has a dev dependency of paragonie/sodium_compat v2.xx. 
So I can't downgrade paragonie/sodium_compat.
I've checked the open PRs and I believe #391 & #384 combined would solve my issues.

```sh
- pusher/pusher-php-server[7.2.0, ..., 7.2.4] 
require paragonie/sodium_compat ^1.6 -> found paragonie/sodium_compat[v1.6.0, ..., v1.21.1] 
but the package is fixed to v2.0.1 (lock file version) by a partial update 
and that version does not match. Make sure you list it as an argument for the update command.
```

**Comment by xinix** [comment]
+1

**Comment by JensLeirens** [comment]
+1

**Comment by sbaeckelant** [comment]
I need this as well. Any news about this?

**Comment by IanSimpson** [comment]
+1 here too... please?

**Comment by BenSeDev** [comment]
For those following this ticket:
https://github.com/pusher/pusher-http-php/pull/391#pullrequestreview-2377803884

PR was approved and will be merged.

❤️

**Comment by aonemd** [comment]
Hey, thank you for reporting the issue. Both PRs are now merged. I'm preparing a release now.

**Comment by aonemd** [comment]
Just made a new release https://github.com/pusher/pusher-http-php/releases/tag/7.2.6

**Comment by BenSeDev** [comment]
Thank you @aonemd 
This help us a lot and is much appreciated!
