### ISSUE TITLE
The 2.2.1 version broke compatibility with PHP 5.3 and lower

### ISSUE THREAD

**Issue by stof** [pusher/pusher-http-php#44]
The composer.json file says that your library supports PHP 5.2+. However, the fix done in https://github.com/pusher/pusher-http-php/pull/40 uses a private function as callback for ``array_walk``, which is only working on PHP 5.4+.

There is 3 ways to fix it:

- bump the minimal version to 5.4 (but this means that any 5.3 user is forced to use a vulnerable version of the library)
- change the ``validate`` method to be public (and documenting it as internal with ``@internal``)
- use a foreach loop over channels instead.

**Comment by WillSewell** [comment]
Thank you for spotting this! We have a fix in this PR https://github.com/pusher/pusher-http-php/pull/45

**Comment by GrahamCampbell** [comment]
This can be closed now.

**Comment by WillSewell** [comment]
:+1:
