### ISSUE TITLE
Namespaces and PSR-4

### ISSUE THREAD

**Issue by GrahamCampbell** [pusher/pusher-http-php#49]
Would you accept a PR to use namespaces and PSR-4 autoloading?

**Comment by vinkla** [comment]
They are for the new (not yet released) version. Check out the [new-lib](https://github.com/pusher/pusher-http-php/tree/new-lib) branch.

**Comment by GrahamCampbell** [comment]
Ah nice.

**Comment by pedzed** [comment]
It hasn't been updated for over a year. Consider reopening the issue?

**Comment by GrahamCampbell** [comment]
This issue isn't really relevant since there's already a "new-lib" branch. Would be pointless for me to re-open it.
