### ISSUE TITLE
Port Acceptance/Integration tests to new-lib

### ISSUE THREAD

**Issue by leggetter** [pusher/pusher-http-php#63]
The 2.x branch has a bunch of acceptance (integration) tests (https://github.com/pusher/pusher-http-php/tree/master/test/acceptance) that have proven highly valuable. These should be ported to the 3.x (new-lib) branch.

**Comment by tanuck** [comment]
Does the travis build have these environment variables available to use on the new-lib branch?

https://github.com/pusher/pusher-http-php/blob/master/test/test_includes.php#L10-L12

**Comment by leggetter** [comment]
@tanuck - these test are used as part of a manual release process. So, the current travis build only runs the unit tests: https://github.com/pusher/pusher-http-php/blob/master/.travis.yml#L15

But, I've just added three environment variables that could be used in future tests:

<img width="734" alt="screen shot 2015-08-12 at 11 39 49" src="https://cloud.githubusercontent.com/assets/328367/9222111/eaf69746-40e6-11e5-8c83-8f8bc8848971.png">

These are named slightly better than the previous variables.

One point to note about the existing tests is that there are a few tests around channel querying that rely on the user opening a browser window and going to the "App Keys" section of an application. Maybe these should be shifted out to be clearly identified as manual tests.

**Comment by WillSewell** [comment]
Closing because we would rather add specific requested features from new-lib to master on a case-by-case basis rather than merging new-lib at this point.
