### ISSUE TITLE
Add logging to 3.0 to at least the same level as 2.0

### ISSUE THREAD

**Issue by leggetter** [pusher/pusher-http-php#68]
Logging has been essential in debugging interactions with the Pusher HTTP API. The 2.0 logging isn't perfect, but it is *really useful*. So we need the at least the same level of logging in 3.0.

The preference would be to be able to set a logger as an option when creating the `Pusher` instance. The logger would implement to https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md

**Comment by tanuck** [comment]
@leggetter how far do you want to go with this? Would you just want to implement a `Pusher::setLogger(PSR3CompliantLogger $logger)` method? Or do you also want to include a PSR3 logger as part of the pusher library?

I would go with the former and maybe add a dependency for a PSR3 logger and use that as the default? Or only log any data if a logger has been set by the user.

**Comment by leggetter** [comment]
I'd suggest we ditch the `setLogger` for this library and instead make it:

```php
$pusher = new Pusher($appId, $appKey, $appSecret, array('logger' => $PSR3CompliantLogger));
```

or something similar depending on what's decided for #66.

By default there's maybe some kind of null logger implementation and a developer can pass in their own implementation to the constructor.

How's that sound?

**Comment by zimbatm** [comment]
All the interactions of the library either give a result or throw an exception. If the user wants to do logging I propose that he wraps the library himself of add his own adapter that basically wraps all the calls with some logging.
