### ISSUE TITLE
get user info from presence channel

### ISSUE THREAD

**Issue by stevenmusumeche** [pusher/pusher-http-php#77]
How can we receive the user info that was provided in our auth endpoint when querying a presence channel?  In auth, I return user info:

```
        $userInfo = array(
            'firstName' => $user->first_name,
            'lastName' => $user->last_name,
            'email' => $user->email,
            'id' => $user->id,
        );
        return $this->pusher->presence_auth($this->request->post('channel_name'), $this->request->post('socket_id'), $user->id, $userInfo);
```

When I later call

`$pusher->get('/channels/presence-1234/users')`

Only the user IDs are returned.

**Comment by hamchapman** [comment]
Currently the REST API doesn't support retrieving user info, only user ids.

Can I ask what your use case is for wanting the user info from the REST API?

**Comment by stevenmusumeche** [comment]
We have two types of "users" which could each have the same ID.  We set a property in auth called "userType" but we can't retrieve that value.

**Comment by zimbatm** [comment]
That's not how presence works, the second subscriber is going to replace the presence info on the user_id when he subscribes. Think of it as a map of user_id => user_data. If a new subscription for the same user_id comes-in then the value of user_data is replaced.

Presence is designed with a single user in mind. 

If you want to maintain presence as a group then either handle that on the UI side (where a group is considered absent if all the user_id containing the group_id left the channel). Or subscribe the users to both a channel where they have the pusher user_id as the application group_id and a channel where they have the pusher user_id as the application user_id.

* "presence-1234" uses the app group_id
* "presence-group-#{group_id}" uses the app user_id 

Then it's possible to query from the group channel, find the presence-group channel and get back the user ids.

**Comment by sburkett** [comment]
I actually have this need as well. The use case is pretty simple, I think. Given selections on a particular form, I want to place the site visitor into the appropriate presence channel. On a backend dashboard, I need to show their form selections as well as their IP address (which I am using as their ID), etc.

**Comment by WillSewell** [comment]
You receive this `user_info` in the auth endpoint when the request is made from the client to authenticate, see: https://pusher.com/docs/rest_api#method-get-channels. You can then store this in your database and retrieve it when required.

**Comment by sburkett** [comment]
Yes, I am aware of that. But as my use case does not involve authenticated users, per se, the database solution is kind of meh. Was hoping just to pull that data in via the `->get` call to get presence users. Looks like I'll need to rethink some things.

**Comment by WillSewell** [comment]
If you have access to the `user_info` in the Pusher auth endpoint, then how come you are not able to access this information from the internal dashboard as well? I feel like I might be misunderstanding your use case...

**Comment by akizor** [comment]
You could overwrite the function 'presence_auth' and prefix the id with a string as an identifier. Like `user.1203`, `user` beeing the model and `1203` the id from database.

**Comment by ajosue** [comment]
i need that too and i understand the solution but let me be honest why you let us save user_info if we cant get it back when need it. the db approach feels like a lazy way.

**Comment by WillSewell** [comment]
Fair enough. However this is not an issue with the PHP library, it is a limitation of the Channels HTTP API. I will pass it on to the Channels product manager as a potential new feature.

**Comment by ihor1010** [comment]
frontend side, I can get all members info with their ids, however, why I can't get it on backend server side?
