### ISSUE TITLE
Replace our HTTP client abstraction by Guzzle

### ISSUE THREAD

**Issue by zimbatm** [pusher/pusher-http-php#95]
It's not worth hitting the same issues when Guzzle already did all the work.

Bonus point for creating a Pusher mock around Guzzle's

Fixes #87

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by rvanlaak** [comment]
Note: the Guzzle client to be used should be passable via the constructor as optional argument, so everyone can keep using their Guzzle middleware.

**Comment by WillSewell** [comment]
Could someone provide me with a list of benefits to _end users_ of the library that using guzzle will bring?

**Comment by elverkilde** [comment]
This was released in version 6.
