### ISSUE TITLE
Cleanup branches?

### ISSUE THREAD

**Issue by vinkla** [pusher/pusher-http-php#96]
Right now there is a lot of branches hanging around. This makes it hard to understand which branch is active and not. Maybe we can simplify them to just `develop` and `master`?

**Comment by simaranjitsingh** [comment]
@vinkla in my opinion, master is always the branch which should be used. This is pretty much standard and everyone follows the same. So, not sure if this cleanup is really required.

**Comment by vinkla** [comment]
I don't think you read it right. Right now there are a lot of branches with weird names left in the repository. We should/could clean them up.

**Comment by vinkla** [comment]
Closing due to age.
